"""
Iteration 2 tests: Auth (JWT), RBAC (admin/asesor), users CRUD, credit reassignment,
reminders, ocupacion field, atendioPor autogenerated, cobranzas filter, backup admin-only.
"""
import os
import pytest
import requests
from datetime import date

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "https://template-builder-156.preview.emergentagent.com").rstrip("/")
API = f"{BASE_URL}/api"


@pytest.fixture(scope="module")
def s():
    return requests.Session()


@pytest.fixture(scope="module")
def state():
    return {}


def _auth(token):
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


# ------------- AUTH -------------
class TestAuth:
    def test_login_admin_success(self, s, state):
        r = s.post(f"{API}/auth/login", json={"username": "admin", "password": "admin123"})
        assert r.status_code == 200, r.text
        d = r.json()
        assert "token" in d and "user" in d
        assert d["user"]["role"] == "admin"
        assert d["user"]["username"] == "admin"
        assert "password_hash" not in d["user"]
        state["admin_token"] = d["token"]
        state["admin_id"] = d["user"]["id"]

    def test_login_wrong_password(self, s):
        r = s.post(f"{API}/auth/login", json={"username": "admin", "password": "wrong"})
        assert r.status_code == 401

    def test_me_without_token(self, s):
        r = s.get(f"{API}/auth/me")
        assert r.status_code == 401

    def test_me_with_token(self, s, state):
        r = s.get(f"{API}/auth/me", headers=_auth(state["admin_token"]))
        assert r.status_code == 200
        assert r.json()["username"] == "admin"


# ------------- USERS (admin only) -------------
class TestUsersAdmin:
    def test_create_asesor_as_admin(self, s, state):
        r = s.post(f"{API}/users", headers=_auth(state["admin_token"]),
                   json={"username": "test_ana", "name": "TEST_Ana Torres",
                         "password": "ana12345", "role": "asesor"})
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["username"] == "test_ana"
        assert d["role"] == "asesor"
        assert d["activo"] is True
        state["asesor_id"] = d["id"]

    def test_login_asesor(self, s, state):
        r = s.post(f"{API}/auth/login", json={"username": "test_ana", "password": "ana12345"})
        assert r.status_code == 200
        state["asesor_token"] = r.json()["token"]

    def test_asesor_cannot_create_user(self, s, state):
        r = s.post(f"{API}/users", headers=_auth(state["asesor_token"]),
                   json={"username": "test_evil", "name": "x", "password": "abcdef", "role": "asesor"})
        assert r.status_code == 403

    def test_asesor_cannot_list_users(self, s, state):
        r = s.get(f"{API}/users", headers=_auth(state["asesor_token"]))
        assert r.status_code == 403


# ------------- CLIENTS + OCUPACION -------------
class TestClientsOcupacion:
    def test_create_client_with_ocupacion(self, s, state):
        r = s.post(f"{API}/clients", headers=_auth(state["admin_token"]),
                   json={"nombre": "TEST_Cliente Uno", "dni": "12345678",
                         "telefono": "987654321", "ocupacion": "Comerciante"})
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["ocupacion"] == "Comerciante"
        state["client_id"] = d["id"]
        # GET verify persistence
        g = s.get(f"{API}/clients/{d['id']}", headers=_auth(state["admin_token"])).json()
        assert g["ocupacion"] == "Comerciante"

    def test_dni_validation_still_works(self, s, state):
        r = s.post(f"{API}/clients", headers=_auth(state["admin_token"]),
                   json={"nombre": "TEST_Bad", "dni": "123"})
        assert r.status_code == 422

    def test_telefono_validation(self, s, state):
        r = s.post(f"{API}/clients", headers=_auth(state["admin_token"]),
                   json={"nombre": "TEST_Bad2", "telefono": "123456789"})
        assert r.status_code == 422

    def test_nombre_required(self, s, state):
        r = s.post(f"{API}/clients", headers=_auth(state["admin_token"]),
                   json={"nombre": ""})
        assert r.status_code == 422


# ------------- CREDITS + ASESOR RBAC -------------
class TestCreditsRBAC:
    def test_admin_creates_credit_assigns_self(self, s, state):
        r = s.post(f"{API}/credits", headers=_auth(state["admin_token"]),
                   json={"clientId": state["client_id"], "capital": 1200, "tasaInteres": 20,
                         "numCuotas": 6, "frecuencia": "Mensual",
                         "fechaInicio": date.today().isoformat()})
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["asesorId"] == state["admin_id"]
        state["credit_admin"] = d["id"]

    def test_asesor_creates_credit_assigns_self(self, s, state):
        r = s.post(f"{API}/credits", headers=_auth(state["asesor_token"]),
                   json={"clientId": state["client_id"], "capital": 600, "tasaInteres": 10,
                         "numCuotas": 3, "frecuencia": "Mensual",
                         "fechaInicio": date.today().isoformat()})
        assert r.status_code == 200, r.text
        d = r.json()
        assert d["asesorId"] == state["asesor_id"]
        state["credit_asesor"] = d["id"]

    def test_asesor_list_credits_only_own(self, s, state):
        r = s.get(f"{API}/credits", headers=_auth(state["asesor_token"]))
        assert r.status_code == 200
        ids = [c["id"] for c in r.json()]
        assert state["credit_asesor"] in ids
        assert state["credit_admin"] not in ids

    def test_admin_list_credits_all(self, s, state):
        r = s.get(f"{API}/credits", headers=_auth(state["admin_token"]))
        assert r.status_code == 200
        ids = [c["id"] for c in r.json()]
        assert state["credit_admin"] in ids
        assert state["credit_asesor"] in ids

    def test_asesor_cannot_access_other_credit(self, s, state):
        r = s.get(f"{API}/credits/{state['credit_admin']}", headers=_auth(state["asesor_token"]))
        assert r.status_code == 403

    def test_asesor_cannot_reassign(self, s, state):
        r = s.patch(f"{API}/credits/{state['credit_admin']}/asesor",
                    headers=_auth(state["asesor_token"]),
                    json={"asesorId": state["asesor_id"]})
        assert r.status_code == 403

    def test_admin_reassigns_credit(self, s, state):
        r = s.patch(f"{API}/credits/{state['credit_admin']}/asesor",
                    headers=_auth(state["admin_token"]),
                    json={"asesorId": state["asesor_id"]})
        assert r.status_code == 200, r.text
        assert r.json()["asesorId"] == state["asesor_id"]
        # verify - asesor now sees it
        g = s.get(f"{API}/credits", headers=_auth(state["asesor_token"])).json()
        assert state["credit_admin"] in [c["id"] for c in g]


# ------------- PAGAR - atendioPor auto -------------
class TestPagoAtendio:
    def test_pagar_atendioPor_is_user_name(self, s, state):
        r = s.post(f"{API}/credits/{state['credit_asesor']}/cuotas/1/pagar",
                   headers=_auth(state["asesor_token"]),
                   json={"capital": 200, "interes": 20, "mora": 0, "metodoPago": "Efectivo"})
        assert r.status_code == 200, r.text
        cuota1 = next(c for c in r.json()["cuotas"] if c["numero"] == 1)
        assert cuota1["estado"] == "Pagada"
        assert cuota1["atendioPor"] == "TEST_Ana Torres"


# ------------- REMINDERS -------------
class TestReminders:
    def test_reminders_structure_asesor(self, s, state):
        r = s.get(f"{API}/reminders", headers=_auth(state["asesor_token"]))
        assert r.status_code == 200
        d = r.json()
        for k in ["vencidas", "hoy", "manana", "semana", "futuro"]:
            assert k in d
        all_items = d["vencidas"] + d["hoy"] + d["manana"] + d["semana"] + d["futuro"]
        # asesor sees only own credits
        for it in all_items:
            assert it["asesorId"] == state["asesor_id"]

    def test_reminders_admin_all(self, s, state):
        r = s.get(f"{API}/reminders", headers=_auth(state["admin_token"]))
        assert r.status_code == 200
        # ok - just check no crash

    def test_mark_reminder_updates_recordadoEn(self, s, state):
        # Find any pending cuota for the asesor's credit
        cr = s.get(f"{API}/credits/{state['credit_asesor']}",
                   headers=_auth(state["asesor_token"])).json()
        pending = next(c for c in cr["cuotas"] if c["estado"] == "Pendiente")
        numero = pending["numero"]
        r = s.post(f"{API}/reminders/mark", headers=_auth(state["asesor_token"]),
                   json={"creditId": state["credit_asesor"], "numero": numero})
        assert r.status_code == 200
        cr2 = s.get(f"{API}/credits/{state['credit_asesor']}",
                    headers=_auth(state["asesor_token"])).json()
        c = next(x for x in cr2["cuotas"] if x["numero"] == numero)
        assert c["recordadoEn"] is not None


# ------------- REPORTS -------------
class TestReports:
    def test_cobranzas_asesor_only_own(self, s, state):
        r = s.get(f"{API}/reports/cobranzas", headers=_auth(state["asesor_token"]))
        assert r.status_code == 200
        for row in r.json()["rows"]:
            assert row["asesor"] == "TEST_Ana Torres"


# ------------- BACKUP -------------
class TestBackup:
    def test_backup_admin(self, s, state):
        r = s.get(f"{API}/backup/export", headers=_auth(state["admin_token"]))
        assert r.status_code == 200
        assert "clients" in r.json()

    def test_backup_asesor_forbidden(self, s, state):
        r = s.get(f"{API}/backup/export", headers=_auth(state["asesor_token"]))
        assert r.status_code == 403


# ------------- CHANGE PASSWORD -------------
class TestChangePassword:
    def test_change_password_wrong_current(self, s, state):
        r = s.post(f"{API}/auth/change-password", headers=_auth(state["asesor_token"]),
                   json={"current_password": "wrong", "new_password": "newpass1"})
        assert r.status_code == 400

    def test_change_password_success(self, s, state):
        r = s.post(f"{API}/auth/change-password", headers=_auth(state["asesor_token"]),
                   json={"current_password": "ana12345", "new_password": "ana67890"})
        assert r.status_code == 200
        # login with new password
        lg = s.post(f"{API}/auth/login", json={"username": "test_ana", "password": "ana67890"})
        assert lg.status_code == 200
        state["asesor_token"] = lg.json()["token"]


# ------------- DELETE USER RULES -------------
class TestDeleteUser:
    def test_cannot_delete_asesor_with_credits(self, s, state):
        r = s.delete(f"{API}/users/{state['asesor_id']}", headers=_auth(state["admin_token"]))
        assert r.status_code == 400

    def test_cannot_delete_admin(self, s, state):
        r = s.delete(f"{API}/users/{state['admin_id']}", headers=_auth(state["admin_token"]))
        assert r.status_code == 400


# ------------- Z CLEANUP -------------
class TestZCleanup:
    def test_delete_credits_and_client(self, s, state):
        # both credits are now asesor's after reassignment
        for cid_key in ("credit_admin", "credit_asesor"):
            s.delete(f"{API}/credits/{state[cid_key]}", headers=_auth(state["admin_token"]))
        s.delete(f"{API}/clients/{state['client_id']}", headers=_auth(state["admin_token"]))
        # now can delete asesor
        r = s.delete(f"{API}/users/{state['asesor_id']}", headers=_auth(state["admin_token"]))
        assert r.status_code == 200
